with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
mockname: "Mock{{.InterfaceName}}"
outpkg: "mocks"
packages:
  github.com/julianoL13/app-game-deal-hunter/game:
    interfaces:
      Writer:
  github.com/julianoL13/app-game-deal-hunter/offer:
    interfaces:
      Writer:
      Reader:
