with-expecter: true
packages:
  github.com/julianoL13/app-game-deal-hunter/game:
    config:
      dir: "{{.InterfaceDir}}/mocks"
      outpkg: "mocks"
      mockname: "Mock{{.InterfaceName}}"
    interfaces:
      writer:
  github.com/julianoL13/app-game-deal-hunter/offer:
    config:
      dir: "{{.InterfaceDir}}/mocks"
      outpkg: "mocks"
      mockname: "Mock{{.InterfaceName}}"
    interfaces:
      writer:
      readerByGameID:
      readerByGameName:
