// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	offer "github.com/julianoL13/app-game-deal-hunter/internal/offer"
)

// MockreaderByGameName is an autogenerated mock type for the readerByGameName type
type MockreaderByGameName struct {
	mock.Mock
}

type MockreaderByGameName_Expecter struct {
	mock *mock.Mock
}

func (_m *MockreaderByGameName) EXPECT() *MockreaderByGameName_Expecter {
	return &MockreaderByGameName_Expecter{mock: &_m.Mock}
}

// FindByGameName provides a mock function with given fields: ctx, name
func (_m *MockreaderByGameName) FindByGameName(ctx context.Context, name string) ([]*offer.Offer, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByGameName")
	}

	var r0 []*offer.Offer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*offer.Offer, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*offer.Offer); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*offer.Offer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockreaderByGameName_FindByGameName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByGameName'
type MockreaderByGameName_FindByGameName_Call struct {
	*mock.Call
}

// FindByGameName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockreaderByGameName_Expecter) FindByGameName(ctx interface{}, name interface{}) *MockreaderByGameName_FindByGameName_Call {
	return &MockreaderByGameName_FindByGameName_Call{Call: _e.mock.On("FindByGameName", ctx, name)}
}

func (_c *MockreaderByGameName_FindByGameName_Call) Run(run func(ctx context.Context, name string)) *MockreaderByGameName_FindByGameName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockreaderByGameName_FindByGameName_Call) Return(_a0 []*offer.Offer, _a1 error) *MockreaderByGameName_FindByGameName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockreaderByGameName_FindByGameName_Call) RunAndReturn(run func(context.Context, string) ([]*offer.Offer, error)) *MockreaderByGameName_FindByGameName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockreaderByGameName creates a new instance of MockreaderByGameName. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockreaderByGameName(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockreaderByGameName {
	mock := &MockreaderByGameName{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
