// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	offer "github.com/julianoL13/app-game-deal-hunter/offer"
)

// MockWriter is an autogenerated mock type for the Writer type
type MockWriter struct {
	mock.Mock
}

type MockWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWriter) EXPECT() *MockWriter_Expecter {
	return &MockWriter_Expecter{mock: &_m.Mock}
}

// Insert provides a mock function with given fields: ctx, _a1
func (_m *MockWriter) Insert(ctx context.Context, _a1 *offer.Offer) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *offer.Offer) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWriter_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockWriter_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *offer.Offer
func (_e *MockWriter_Expecter) Insert(ctx interface{}, _a1 interface{}) *MockWriter_Insert_Call {
	return &MockWriter_Insert_Call{Call: _e.mock.On("Insert", ctx, _a1)}
}

func (_c *MockWriter_Insert_Call) Run(run func(ctx context.Context, _a1 *offer.Offer)) *MockWriter_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*offer.Offer))
	})
	return _c
}

func (_c *MockWriter_Insert_Call) Return(_a0 error) *MockWriter_Insert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWriter_Insert_Call) RunAndReturn(run func(context.Context, *offer.Offer) error) *MockWriter_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWriter creates a new instance of MockWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWriter {
	mock := &MockWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
