// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	offer "github.com/julianoL13/app-game-deal-hunter/offer"
	mock "github.com/stretchr/testify/mock"
)

// Mockwriter is an autogenerated mock type for the writer type
type Mockwriter struct {
	mock.Mock
}

type Mockwriter_Expecter struct {
	mock *mock.Mock
}

func (_m *Mockwriter) EXPECT() *Mockwriter_Expecter {
	return &Mockwriter_Expecter{mock: &_m.Mock}
}

// Save provides a mock function with given fields: ctx, _a1
func (_m *Mockwriter) Save(ctx context.Context, _a1 *offer.Offer) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *offer.Offer) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mockwriter_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type Mockwriter_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *offer.Offer
func (_e *Mockwriter_Expecter) Save(ctx interface{}, _a1 interface{}) *Mockwriter_Save_Call {
	return &Mockwriter_Save_Call{Call: _e.mock.On("Save", ctx, _a1)}
}

func (_c *Mockwriter_Save_Call) Run(run func(ctx context.Context, _a1 *offer.Offer)) *Mockwriter_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*offer.Offer))
	})
	return _c
}

func (_c *Mockwriter_Save_Call) Return(_a0 error) *Mockwriter_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mockwriter_Save_Call) RunAndReturn(run func(context.Context, *offer.Offer) error) *Mockwriter_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockwriter creates a new instance of Mockwriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockwriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mockwriter {
	mock := &Mockwriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
