// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	offer "github.com/julianoL13/app-game-deal-hunter/offer"

	uuid "github.com/google/uuid"
)

// MockReader is an autogenerated mock type for the Reader type
type MockReader struct {
	mock.Mock
}

type MockReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReader) EXPECT() *MockReader_Expecter {
	return &MockReader_Expecter{mock: &_m.Mock}
}

// FindByGameID provides a mock function with given fields: ctx, gameID
func (_m *MockReader) FindByGameID(ctx context.Context, gameID uuid.UUID) ([]*offer.Offer, error) {
	ret := _m.Called(ctx, gameID)

	if len(ret) == 0 {
		panic("no return value specified for FindByGameID")
	}

	var r0 []*offer.Offer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*offer.Offer, error)); ok {
		return rf(ctx, gameID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*offer.Offer); ok {
		r0 = rf(ctx, gameID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*offer.Offer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, gameID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReader_FindByGameID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByGameID'
type MockReader_FindByGameID_Call struct {
	*mock.Call
}

// FindByGameID is a helper method to define mock.On call
//   - ctx context.Context
//   - gameID uuid.UUID
func (_e *MockReader_Expecter) FindByGameID(ctx interface{}, gameID interface{}) *MockReader_FindByGameID_Call {
	return &MockReader_FindByGameID_Call{Call: _e.mock.On("FindByGameID", ctx, gameID)}
}

func (_c *MockReader_FindByGameID_Call) Run(run func(ctx context.Context, gameID uuid.UUID)) *MockReader_FindByGameID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockReader_FindByGameID_Call) Return(_a0 []*offer.Offer, _a1 error) *MockReader_FindByGameID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReader_FindByGameID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*offer.Offer, error)) *MockReader_FindByGameID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByGameName provides a mock function with given fields: ctx, name
func (_m *MockReader) FindByGameName(ctx context.Context, name string) ([]*offer.Offer, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByGameName")
	}

	var r0 []*offer.Offer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*offer.Offer, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*offer.Offer); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*offer.Offer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReader_FindByGameName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByGameName'
type MockReader_FindByGameName_Call struct {
	*mock.Call
}

// FindByGameName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockReader_Expecter) FindByGameName(ctx interface{}, name interface{}) *MockReader_FindByGameName_Call {
	return &MockReader_FindByGameName_Call{Call: _e.mock.On("FindByGameName", ctx, name)}
}

func (_c *MockReader_FindByGameName_Call) Run(run func(ctx context.Context, name string)) *MockReader_FindByGameName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockReader_FindByGameName_Call) Return(_a0 []*offer.Offer, _a1 error) *MockReader_FindByGameName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReader_FindByGameName_Call) RunAndReturn(run func(context.Context, string) ([]*offer.Offer, error)) *MockReader_FindByGameName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReader creates a new instance of MockReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReader {
	mock := &MockReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
