// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	offer "github.com/julianoL13/app-game-deal-hunter/offer"

	uuid "github.com/google/uuid"
)

// MockreaderByGameID is an autogenerated mock type for the readerByGameID type
type MockreaderByGameID struct {
	mock.Mock
}

type MockreaderByGameID_Expecter struct {
	mock *mock.Mock
}

func (_m *MockreaderByGameID) EXPECT() *MockreaderByGameID_Expecter {
	return &MockreaderByGameID_Expecter{mock: &_m.Mock}
}

// FindByGameID provides a mock function with given fields: ctx, gameID
func (_m *MockreaderByGameID) FindByGameID(ctx context.Context, gameID uuid.UUID) ([]*offer.Offer, error) {
	ret := _m.Called(ctx, gameID)

	if len(ret) == 0 {
		panic("no return value specified for FindByGameID")
	}

	var r0 []*offer.Offer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*offer.Offer, error)); ok {
		return rf(ctx, gameID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*offer.Offer); ok {
		r0 = rf(ctx, gameID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*offer.Offer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, gameID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockreaderByGameID_FindByGameID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByGameID'
type MockreaderByGameID_FindByGameID_Call struct {
	*mock.Call
}

// FindByGameID is a helper method to define mock.On call
//   - ctx context.Context
//   - gameID uuid.UUID
func (_e *MockreaderByGameID_Expecter) FindByGameID(ctx interface{}, gameID interface{}) *MockreaderByGameID_FindByGameID_Call {
	return &MockreaderByGameID_FindByGameID_Call{Call: _e.mock.On("FindByGameID", ctx, gameID)}
}

func (_c *MockreaderByGameID_FindByGameID_Call) Run(run func(ctx context.Context, gameID uuid.UUID)) *MockreaderByGameID_FindByGameID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockreaderByGameID_FindByGameID_Call) Return(_a0 []*offer.Offer, _a1 error) *MockreaderByGameID_FindByGameID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockreaderByGameID_FindByGameID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*offer.Offer, error)) *MockreaderByGameID_FindByGameID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockreaderByGameID creates a new instance of MockreaderByGameID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockreaderByGameID(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockreaderByGameID {
	mock := &MockreaderByGameID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
